name: cd

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  if_merged:    
    if: github.event.pull_request.merged == true  
    runs-on: self-hosted
    steps:
        
      - 
        name: Checkout Repository
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: iljapidonenko/simple-typescript:latest